version: '3.7'

services:
  app:
    build:
      context: ./docker/apache2
    ports:
      - '80:80'
    volumes:
      - ./www:/www:cached
    tty: true
    stdin_open: true
  mysql:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
